name: topics channel

on:
  push:
    branches: [ "main" ]

jobs:
  build-runner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: dorny/paths-filter@v2.11.1
      id: changes
      with:
        filters: |
          dockerfile:
            - 'channels/topics/bot/Dockerfile'
    - if: steps.changes.outputs.dockerfile == 'true'
      name: Log in to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - if: steps.changes.outputs.dockerfile == 'true'
      name: Build and push Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: channels/topics/bot
        file: channels/topics/bot/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/topics-bot-runner
