name: topics channel

on:
  push:
    branches: [ "main" ]
    paths:
    - "channels/topics/**"

jobs:
  build-runner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: dorny/paths-filter@v2.11.1
      id: changes
      with:
        filters: |
          runner:
            - 'channels/topics/runner/**'
    - if: steps.changes.outputs.runner == 'true'
      name: Log in to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - if: steps.changes.outputs.runner == 'true'
      id: git-short-sha
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - if: steps.changes.outputs.runner == 'true'
      name: Build and push Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: channels/topics/runner
        file: channels/topics/runner/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/topics-runner:latest,${{ secrets.DOCKERHUB_USERNAME }}/topics-runner:${{ steps.git-short-sha.outputs.sha_short }}
  
  build-bot:
    needs: build-runner
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: dorny/paths-filter@v2.11.1
      id: changes
      with:
        filters: |
          bot:
            - 'channels/topics/bot/**'
            - 'channels/topics/runner/**'
    - if: steps.changes.outputs.bot == 'true'
      name: Log in to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - if: steps.changes.outputs.bot == 'true'
      id: git-short-sha
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - if: steps.changes.outputs.bot == 'true'
      name: Build and push Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: channels/topics/bot
        file: channels/topics/bot/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/topics-bot:latest,${{ secrets.DOCKERHUB_USERNAME }}/topics-bot:${{ steps.git-short-sha.outputs.sha_short }}
  
  generate-video:
    needs: build-bot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: dorny/paths-filter@v2.11.1
      id: changes
      with:
        filters: |
          output:
            - 'channels/topics/output/videos.txt'
    - if: steps.changes.outputs.output == 'true'
      run: |
        before_md5="$(md5sum channels/topics/output/videos.txt)" || exit 1
        docker run --rm -v "$(pwd)/channels/topics/output:/work" --workdir /work ${{ secrets.DOCKERHUB_USERNAME }}/topics-bot --input-file /work/videos.txt || exit 1
        after_md5="$(md5sum channels/topics/output/videos.txt)" || exit 1
        [[ "$before_md5" == "$after_md5" ]] || {
          git config user.name github-actions || exit 1
          git config user.email github-actions@github.com || exit 1
          git add channels/topics/output/videos.txt || exit 1
          git commit -m "generated" || exit 1
          git push || exit 1
        }
    - if: steps.changes.outputs.output == 'true'
      uses: actions/upload-artifact@v3.1.3
      with:
        path: channels/topics/output/
        
